language: node_js
sudo: false
node_js:
- '12'
env:
  global:
    - LOG_TEST_COVERAGE=true
cache: yarn
script: yarn run test
before_deploy: yarn run build
deploy:
  provider: npm
  email: sendstufftokevin@gmail.com
  on:
    branch: master
    tags: true
  skip_cleanup: true
  edge: true # https://docs.travis-ci.com/user/deployment-v2
  api_key:
    secure: hglZFImCQ60GfaKlnPA8aDgMauE5Q3vK84Jd0Y8UZKtzomciWy/wxPMDc3zqzqKvdKX2W7RIxbJolnCdwQYj+Ih1tSAtgFJUMXSLOaSHmbUrRD4tQgywRiJ1muZCrUn6w2rwZLFLWmMGEqmQyz+1OFjhtS6VFVPBO+XtcGbEXvZ9nK9AAZVWS/f9lHK65k+wnLvVIoXVVSg2cmDcdAwJ54UWyPNyS4+N3EHiwscQr4uZl2+PK4vAQQ3CvSm4odi6N9rkVlu86P1rkjxU6B4Au7lMA9LxGAirvgL4jGNkTIwqTWINsfHPCtIa3h6SIU34FiJXk5EMwjl+mlLhUy7CQrEgzZkJtvPI/LjQahUKtBXSGHgqbcYuLN8lm/dNcWUJpsSVHc/ZdIvtcviQk9OnrsC1rCSo1ns/InWMpiOk1oyoXgEI9dFzecgdmBMlYeYmnQMOj77QVU6rQ7weAjNXxYF8ZvZhDXW+tWm14nmDvhY4WmXaWsjqbiyRsXjVD4ZCIE8gmhn+WLncFTdr6ArtG0YyUx+nBY9lei2w5GK9Gyu4S0iDqEc5W+s+iCCZ0+/Z2KQYKRnZjUL234I44BgS0E1c+PAEgopWkf1GVouf9MY8EveivjlaZiHDwDfqjHqo0X0RdvjDN+WyH9aLWpzdBX3lVopbrnUTn5NHVig1DWw=
