language: node_js
sudo: false
node_js:
- '12'
env:
  global:
    - LOG_TEST_COVERAGE=true
cache: yarn
script: yarn run test
before_deploy: yarn run build
deploy:
  provider: npm
  email: sendstufftokevin@gmail.com
  api_key:
    secure: H1Dy8nUDWAwLe8esMejYc5N/d/VOgM72aEL5PibOEUnY6zRzTcJYUJlJDVSCAkObNtqqS1L0sf3qOspTPwN0eFWmOvh+cL4pBGfxciVzVPPdBCznzvWNUqsv4tRn4Os+H/BgfW1o/EKfw/Fp6+wFtmbYH1Vd+pCQMDLVC0D1zFVMl5/rkLrTgsS7g94rvbokOI25pYRoykYnn56n2ClZDdcSELWmOax4u28P1a/NZnUMxkuYHmEJN/hCP0m1Q8x+qMn4dj3s8lx0DxpeXDq8eR0atzlvzxlQlirjmnN741MuC20cw3IlYKFeFGsn+r2lgOYT+ZC0BQCZyRqcccglcX3yS/rc9bj6rnnaZqawN4XRHvXGpPLlFgQqYL6Fm88SzdFtA2v5tkP3pKXAKH4eAJtFbZfE5vydNZjRs+MU7BgAAu1kCXFmdXbXYTD/REye8JAg9lPNL7mWTQfoohtIkq+vmu5XOtwtYjTlfqbJCwsjTMcBT6bVcf/77sAbmtcIukH1eLjA5N2V96PB0ff8ymM03NYgOIGD+cWXUkcprn2zZm4POklmQ/XC1FQITWscvpXQMpDPT93N9eGebrNmzj2AGMK1+qlb21zPwzedDbxEJ6FBeslkxdV4dTgTY5SNLf/afKtpQFxSi8m3BkqH160sRkXF0vNtulMLkbx4kF0=
  on:
    branch: master
    tags: true
  skip_cleanup: true
  edge: true # https://docs.travis-ci.com/user/deployment-v2
