name: Unit test, log code coverage, and build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LOG_TEST_COVERAGE: true
    steps:
    - uses: actions/checkout@v2
    - name: Run tests and build on Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn install
    - run: yarn test
    - run: yarn run build
